version: '3'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "5775:5775/udp" # Agent
      - "6831:6831/udp" # Agent
      - "6832:6832/udp" # Agent
      - "4317:4317"     # gRPC Collector
      - "16686:16686"   # Web UI
